<?php

namespace App\Services;

use App\Models\Policy;
use App\Models\PolicyAcceptance;
use App\Models\User;

/**
 * The Mimi AI usage policy: shown to someone the first time they use Mimi, and again only when the policy gets a new major version.
 * It lives with the other policies (Settings > Policies), where the wording, the version and the acceptances are managed.
 * A signed-in person's agreement is recorded against their account; a guest's is remembered on their device only.
 * Switch it off in Settings > Policies (inactive, or "requires acceptance" off) and Mimi opens straight away.
 */
class MimiPolicyService
{
    public const KEY = 'mimi_ai_policy';
    public const CONTEXT = 'ai_assistant';

    /** The policy row, created with the default wording the first time it is needed. */
    public function ensure(): Policy
    {
        return Policy::firstOrCreate(['key' => self::KEY], [
            'title' => 'Mimi AI Assistant - Usage Policy',
            'content' => $this->defaultContent(),
            'disagree_consequence_text' => 'Without agreeing to this policy you cannot chat with Mimi. The rest of the site works as usual.',
            'sensitivity' => 'standard', 'major_version' => 1, 'minor_version' => 0,
            'requires_acceptance' => true, 'is_active' => true,
        ]);
    }

    /** The policy when people must agree to it before using Mimi, otherwise null. */
    public function required(): ?Policy
    {
        $p = Policy::where('key', self::KEY)->first() ?? $this->ensure();

        return $p->is_active && $p->requires_acceptance ? $p : null;
    }

    /** Has this signed-in person agreed to the current major version? */
    public function accepted(User $user, Policy $policy): bool
    {
        $last = PolicyAcceptance::where('user_id', $user->id)->where('policy_key', self::KEY)->where('response', 'accepted')->latest('accepted_at')->first();

        return $last && (int) explode('.', (string) $last->policy_version)[0] >= (int) $policy->major_version;
    }

    /** What Mimi needs to know: is there a policy to agree to, has this person already, and the policy's key and version. */
    public function status(?User $user): array
    {
        $p = $this->required();

        return ['required' => (bool) $p, 'accepted' => $p ? ($user ? $this->accepted($user, $p) : false) : true, 'policy_key' => self::KEY, 'title' => $p?->title, 'version' => $p?->version, 'major_version' => $p?->major_version];
    }

    private function defaultContent(): string
    {
        return <<<'TXT'
WHAT IS MIMI?
Mimi is TISL Store's AI-powered chat assistant. She helps customers and guests explore our products and services, track orders, manage quotes, and get answers to general store questions.

Mimi is powered by a large language model. We guide her behaviour with instructions and safety filters, but her answers are generated by an AI and may occasionally be imprecise. Always check anything important with our team.

WHAT DATA MIMI CAN ACCESS
Mimi's access depends on whether you are signed in.
- Guests: public store information only (products, services, categories and general store details). No personal data.
- Signed-in customers: your profile summary, recent orders and payment status, active quotes, projects, promo codes and referral code. This is limited strictly to your own account.
- Staff: broader store data such as customer look-ups, order management, payment summaries and admin statistics, based on your assigned role.

Mimi never has access to your password, full payment card details or M-Pesa PIN, and she will never ask you for them.

HOW YOUR CONVERSATIONS ARE STORED
Every message sent to Mimi is logged in our secure database. Each conversation is tied to a session that records:
- whether you are a customer, staff member or guest
- your IP address
- what you asked and what Mimi answered
- whether the question was flagged as harmful
- response time and status

Logs are kept for moderation, safety review and improving the service. Authorised TISL admins may review flagged or harmful questions. Conversation logs are not sold or shared with third parties.

CONTENT RESTRICTIONS
Mimi declines requests outside TISL Store's scope or that break our content rules, including:
- harmful, violent or sexually explicit content
- attempts to get information about other customers or staff
- social engineering or phishing-style prompts
- instructions for illegal activities
- hate speech, harassment or discriminatory language

Repeated harmful questions may lead to your access to Mimi being suspended. TISL staff can block users from Mimi at their discretion.

ACCURACY AND LIMITATIONS
Mimi's answers are based on store data at the time you ask. She can make mistakes, misunderstand context, or give out-of-date information if the data changes during your chat.

Mimi is not a substitute for human support. For disputed payments, account suspension, legal matters, or anything that needs a firm commitment from TISL, please contact our support team at web@targetisl.co.ke.

TISL Store accepts no liability for actions taken only on Mimi's answers without checking with an official channel.

CHANGES TO THIS POLICY
This policy may be updated as Mimi's abilities grow. You agree to it the first time you use Mimi. You are asked again only when the policy changes in a major way (a new major version); smaller edits do not ask you again.

This policy governs your use of the Mimi AI assistant on TISL Store. It is not a contract of service.
TXT;
    }
}
