<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Invoice {{ $invoice->invoice_number }}</title>
  <style>
    body      { font-family: Arial, sans-serif; background: #f4f4f5; margin: 0; padding: 24px; color: #111; }
    .card     { background: #fff; max-width: 640px; margin: 0 auto; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,.12); }
    .header   { background: #7c3aed; color: #fff; padding: 28px 32px; }
    .header h1{ margin: 0; font-size: 22px; }
    .header p { margin: 4px 0 0; opacity: .85; font-size: 13px; }
    .body     { padding: 28px 32px; }
    .meta     { display: flex; gap: 32px; margin-bottom: 24px; font-size: 13px; color: #555; }
    .meta div strong { display: block; color: #111; font-size: 14px; }
    table     { width: 100%; border-collapse: collapse; font-size: 14px; margin-bottom: 20px; }
    th        { text-align: left; padding: 8px 10px; border-bottom: 2px solid #e5e7eb; color: #555; font-size: 12px; text-transform: uppercase; }
    td        { padding: 10px; border-bottom: 1px solid #f0f0f0; }
    .totals   { text-align: right; font-size: 14px; }
    .totals .row { display: flex; justify-content: flex-end; gap: 24px; padding: 4px 0; }
    .totals .total-row { font-weight: bold; font-size: 16px; color: #7c3aed; border-top: 2px solid #e5e7eb; padding-top: 8px; margin-top: 4px; }
    .note     { background: #f9f5ff; border-left: 3px solid #a855f7; padding: 12px 16px; font-size: 13px; color: #555; margin-top: 20px; border-radius: 0 4px 4px 0; }
    .footer   { padding: 20px 32px; font-size: 12px; color: #888; border-top: 1px solid #f0f0f0; text-align: center; }
    .badge    { display: inline-block; padding: 2px 10px; border-radius: 99px; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: .5px; }
    .badge-sent    { background: #dbeafe; color: #1d4ed8; }
    .badge-paid    { background: #dcfce7; color: #16a34a; }
    .badge-overdue { background: #fee2e2; color: #dc2626; }
    .badge-draft   { background: #f3f4f6; color: #6b7280; }
  </style>
</head>
<body>
  <div class="card">

    {{-- Header --}}
    <div class="header">
      <h1>Invoice {{ $invoice->invoice_number }}</h1>
      <p>TISL Industrial Solutions</p>
    </div>

    <div class="body">

      {{-- Meta row --}}
      <div class="meta">
        <div>
          <span>Billed to</span>
          <strong>{{ $customer->name }}</strong>
          @if($customer->email)
            <span>{{ $customer->email }}</span>
          @endif
        </div>
        <div>
          <span>Invoice date</span>
          <strong>{{ $invoice->created_at->format('d M Y') }}</strong>
        </div>
        @if($invoice->due_date)
        <div>
          <span>Due date</span>
          <strong>{{ $invoice->due_date->format('d M Y') }}</strong>
        </div>
        @endif
        <div>
          <span>Status</span>
          <strong>
            <span class="badge badge-{{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span>
          </strong>
        </div>
      </div>

      {{-- Line items --}}
      <table>
        <thead>
          <tr>
            <th>Description</th>
            <th style="text-align:right">Amount</th>
          </tr>
        </thead>
        <tbody>
          @foreach($invoice->items as $item)
          <tr>
            <td>{{ $item->description }}</td>
            <td style="text-align:right">
              {{ $invoice->currency?->symbol ?? 'KES' }}
              {{ number_format($item->amount, 2) }}
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>

      {{-- Totals --}}
      <div class="totals">
        <div class="row">
          <span>Subtotal</span>
          <span>{{ $invoice->currency?->symbol ?? 'KES' }} {{ number_format($invoice->subtotal, 2) }}</span>
        </div>
        @if($invoice->interest_amount > 0)
        <div class="row">
          <span>Interest</span>
          <span>{{ $invoice->currency?->symbol ?? 'KES' }} {{ number_format($invoice->interest_amount, 2) }}</span>
        </div>
        @endif
        <div class="row total-row">
          <span>Total Due</span>
          <span>{{ $invoice->currency?->symbol ?? 'KES' }} {{ number_format($invoice->total, 2) }}</span>
        </div>
      </div>

      {{-- Note --}}
      @if($invoice->note)
      <div class="note">
        <strong>Note:</strong> {{ $invoice->note }}
      </div>
      @endif

    </div>

    <div class="footer">
      This invoice was generated by TISL Industrial Solutions. For queries contact your account manager.
    </div>

  </div>
</body>
</html>