<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Api\Traits\LogsReferralActivity;
use App\Models\ReferralCode;
use App\Models\Customer;
use App\Models\Order;
use App\Models\HamperOrder;
use App\Services\PromoCodeService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class PromoCodeController extends Controller
{
    use LogsReferralActivity; 
    protected PromoCodeService $service;

    public function __construct(PromoCodeService $service)
    {
        $this->service = $service;
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — LIST
    // ═══════════════════════════════════════════════════

    /**
     * GET /admin/promo-codes
     * List all non-referral promo codes with filters.
     */
    public function index(Request $request)
    {
        $query = ReferralCode::with(['targetCustomer.user', 'createdBy'])
            ->whereNotIn('type', ['customer_referral']); // exclude personal referral codes

        // Search
        if ($request->filled('search')) {
            $s = $request->search;
            $query->where(function ($q) use ($s) {
                $q->where('code', 'like', "%{$s}%")
                  ->orWhere('name', 'like', "%{$s}%")
                  ->orWhere('description', 'like', "%{$s}%");
            });
        }

        // Filters
        if ($request->filled('type'))        $query->where('type', $request->type);
        if ($request->filled('event_type'))  $query->where('event_type', $request->event_type);
        if ($request->filled('status'))      $query->where('status', $request->status);
        if ($request->filled('reward_type')) $query->where('reward_type', $request->reward_type);
        if ($request->boolean('public'))     $query->where('is_public', true);
        if ($request->boolean('auto'))       $query->where('auto_generated', true);
        if ($request->boolean('expiring'))   $query->expiringSoon(7);

        // Target customer filter
        if ($request->filled('customer_id')) {
            $query->where('target_customer_id', $request->customer_id);
        }

        // Sort
        $allowed = ['name', 'code', 'type', 'event_type', 'status', 'times_used', 'total_revenue', 'created_at', 'valid_until'];
        $sortBy  = in_array($request->input('sort_by'), $allowed)
            ? $request->input('sort_by')
            : 'created_at';
        $query->orderBy($sortBy, $request->input('sort_order', 'desc'));

        $perPage = (int) $request->input('per_page', 20);
        return response()->json($query->paginate($perPage));
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — STATISTICS
    // ═══════════════════════════════════════════════════

    /**
     * GET /admin/promo-codes/statistics
     */
    public function statistics()
    {
        $base = ReferralCode::whereNotIn('type', ['customer_referral']);

        $byEventType = (clone $base)
            ->selectRaw('event_type, COUNT(*) as count, SUM(times_used) as uses, SUM(total_revenue) as revenue')
            ->groupBy('event_type')
            ->get();

        $autoGenerated = (clone $base)->where('auto_generated', true)->count();
        $adminCreated  = (clone $base)->where('auto_generated', false)->count();

        return response()->json([
            'counts' => [
                'total'         => (clone $base)->count(),
                'active'        => (clone $base)->where('status', 'active')->count(),
                'expired'       => (clone $base)->where('status', 'expired')->count(),
                'depleted'      => (clone $base)->where('status', 'depleted')->count(),
                'auto_generated'=> $autoGenerated,
                'admin_created' => $adminCreated,
                'expiring_soon' => (clone $base)->expiringSoon(7)->count(),
            ],
            'totals' => [
                'revenue'        => (clone $base)->sum('total_revenue'),
                'discount_given' => (clone $base)->sum('total_discount_given'),
                'total_uses'     => (clone $base)->sum('times_used'),
                'orders'          => (clone $base)->sum('total_orders'),  
                'avg_order_value' => (clone $base)->avg('average_order_value'), 
            ],
            'by_event_type'  => $byEventType,
            'top_by_revenue' => (clone $base)->orderBy('total_revenue', 'desc')->limit(5)
                ->get(['id', 'name', 'code', 'event_type', 'total_revenue', 'times_used']),
        ]);
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — SHOW SINGLE
    // ═══════════════════════════════════════════════════

    /**
     * GET /admin/promo-codes/{id}
     */
    public function show($id)
    {
        $code = ReferralCode::with([
            'targetCustomer.user',
            'createdBy',
            'updatedBy',
        ])->findOrFail($id);

        return response()->json(['code' => $code]);
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — CREATE
    // ═══════════════════════════════════════════════════

    /**
     * POST /admin/promo-codes
     * Create a manual admin promo code (seasonal, flash sale, bulk, general).
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'                      => 'required|string|max:255',
            'code'                      => 'nullable|string|max:50|unique:referral_codes,code',
            'description'               => 'nullable|string',
            'type'                      => 'required|in:general,first_time,bulk_order,vip,birthday,event,seasonal,flash_sale',
            'event_type'                => 'nullable|in:birthday,first_time,vip_upgrade,loyalty_milestone,win_back,seasonal,flash_sale,bulk_order,general',
            'target_customer_id'        => 'nullable|exists:customers,id',
            'reward_type'               => 'required|in:percentage,fixed_amount,free_shipping,store_credit',
            'reward_value'              => 'required|numeric|min:0',
            'max_uses'                  => 'nullable|integer|min:1',
            'max_uses_per_customer'     => 'nullable|integer|min:1',
            'valid_from'                => 'nullable|date',
            'valid_until'               => 'nullable|date|after:valid_from',
            'min_order_value'           => 'nullable|numeric|min:0',
            'min_items'                 => 'nullable|integer|min:1',
            'stackable'                 => 'boolean',
            'is_public'                 => 'boolean',
            'auto_apply'                => 'boolean',
            'applicable_categories'     => 'nullable|array',
            'applicable_products'       => 'nullable|array',
            'excluded_products'         => 'nullable|array',
            'applicable_customer_types' => 'nullable|array',
            'applicable_tiers'          => 'nullable|array',
            'promo_color'               => 'nullable|string|max:20',
            'display_tags'              => 'nullable|array',
            'admin_notes'               => 'nullable|string',
            'status'                    => 'nullable|in:draft,active,paused',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        DB::beginTransaction();
        try {
            $code = ReferralCode::create([
                ...$request->only([
                    'name', 'description', 'type', 'event_type',
                    'target_customer_id', 'reward_type', 'reward_value',
                    'max_uses', 'max_uses_per_customer',
                    'valid_from', 'valid_until',
                    'min_order_value', 'min_items',
                    'stackable', 'is_public', 'auto_apply',
                    'applicable_categories', 'applicable_products',
                    'excluded_products', 'applicable_customer_types',
                    'applicable_tiers', 'promo_color', 'display_tags',
                    'admin_notes',
                ]),
                'code'                 => $request->code
                                            ? strtoupper($request->code)
                                            : ReferralCode::generateUniqueCode(10),
                'status'               => $request->input('status', 'active'),
                'auto_generated'       => false,
                'referrer_reward_type' => 'none',
                'referrer_reward_value'=> 0,
                'created_by'           => $request->user()->id,
                'updated_by'           => $request->user()->id,
            ]);

            DB::commit();

            $this->logPromoCreated($code);

            return response()->json([
                'message' => 'Promo code created successfully.',
                'code'    => $code->load(['targetCustomer.user', 'createdBy']),
            ], 201);

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Promo code creation failed: ' . $e->getMessage());
            return response()->json(['message' => 'Failed to create promo code.'], 500);
        }
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — UPDATE
    // ═══════════════════════════════════════════════════

    /**
     * PUT /admin/promo-codes/{id}
     */
    public function update(Request $request, $id)
    {
        $code = ReferralCode::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'name'                      => 'sometimes|string|max:255',
            'code'                      => 'sometimes|string|max:50|unique:referral_codes,code,' . $id,
            'description'               => 'nullable|string',
            'reward_type'               => 'sometimes|in:percentage,fixed_amount,free_shipping,store_credit',
            'reward_value'              => 'sometimes|numeric|min:0',
            'max_uses'                  => 'nullable|integer|min:1',
            'max_uses_per_customer'     => 'nullable|integer|min:1',
            'valid_from'                => 'nullable|date',
            'valid_until'               => 'nullable|date',
            'min_order_value'           => 'nullable|numeric|min:0',
            'min_items'                 => 'nullable|integer|min:1',
            'stackable'                 => 'boolean',
            'is_public'                 => 'boolean',
            'auto_apply'                => 'boolean',
            'applicable_categories'     => 'nullable|array',
            'applicable_products'       => 'nullable|array',
            'excluded_products'         => 'nullable|array',
            'applicable_customer_types' => 'nullable|array',
            'applicable_tiers'          => 'nullable|array',
            'promo_color'               => 'nullable|string|max:20',
            'display_tags'              => 'nullable|array',
            'admin_notes'               => 'nullable|string',
        ]);

        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }

        $changes = [];
        $fields  = ['name','code','description','reward_type','reward_value',
                    'max_uses','valid_from','valid_until','min_order_value','status'];
        foreach ($fields as $field) {
            if ($request->has($field) && $request->$field != $code->$field) {
                $changes[] = ['field' => $field, 'old' => $code->$field, 'new' => $request->$field];
            }
        }


        $code->update([
            ...$request->only([
                'name', 'code', 'description',
                'reward_type', 'reward_value',
                'max_uses', 'max_uses_per_customer',
                'valid_from', 'valid_until',
                'min_order_value', 'min_items',
                'stackable', 'is_public', 'auto_apply',
                'applicable_categories', 'applicable_products',
                'excluded_products', 'applicable_customer_types',
                'applicable_tiers', 'promo_color', 'display_tags',
                'admin_notes',
            ]),
            'updated_by' => $request->user()->id,
        ]);

        if (!empty($changes)) {
            $this->logPromoUpdated($code, $changes); 
        }

        return response()->json([
            'message' => 'Promo code updated.',
            'code'    => $code->fresh(['targetCustomer.user', 'createdBy']),
        ]);
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — DELETE
    // ═══════════════════════════════════════════════════

    /**
     * DELETE /admin/promo-codes/{id}
     */
    public function destroy($id)
    {
        $code = ReferralCode::findOrFail($id);

        if ($code->times_used > 0) {
            $code->update(['status' => 'archived']);
            $this->logPromoStatusChanged($code, 'ARCHIVED');
            return response()->json([
                'message' => 'Code has been used — archived instead of deleted.',
                'code'    => $code,
            ]);
        }

        $this->logPromoStatusChanged($code, 'DELETED');
        $code->delete();
        return response()->json(['message' => 'Promo code deleted.']);
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — STATUS MANAGEMENT
    // ═══════════════════════════════════════════════════

    /**
     * POST /admin/promo-codes/{id}/activate
     */
    public function activate(Request $request, $id)
    {
        $code = ReferralCode::findOrFail($id);
        $code->activate();
        $code->update(['updated_by' => $request->user()->id]);
        $this->logPromoStatusChanged($code, 'ACTIVATED'); 
        return response()->json(['message' => 'Code activated.', 'code' => $code]);
    }

    /**
     * POST /admin/promo-codes/{id}/pause
     */
    public function pause(Request $request, $id)
    {
        $code = ReferralCode::findOrFail($id);
        $code->pause();
        $code->update(['updated_by' => $request->user()->id]);
        $this->logPromoStatusChanged($code, 'PAUSED'); 
        return response()->json(['message' => 'Code paused.', 'code' => $code]);
    }

    /**
     * POST /admin/promo-codes/{id}/archive
     */
    public function archive(Request $request, $id)
    {
        $code = ReferralCode::findOrFail($id);
        $code->archive();
        $code->update(['updated_by' => $request->user()->id]);
        $this->logPromoStatusChanged($code, 'ARCHIVED');
        return response()->json(['message' => 'Code archived.', 'code' => $code]);
    }

    // ═══════════════════════════════════════════════════
    // ADMIN — MANUAL TRIGGER GENERATORS
    // ═══════════════════════════════════════════════════

    /**
     * POST /admin/promo-codes/generate-birthday
     * Manually trigger birthday code generation (e.g. for testing).
     */
    public function triggerBirthday()
    {
        $stats = $this->service->generateBirthdayCodes(daysAhead: 0);
        return response()->json([
            'message' => 'Birthday code generation complete.',
            'stats'   => $stats,
        ]);
    }

    /**
     * POST /admin/promo-codes/generate-winback
     * Manually trigger win-back code generation.
     */
    public function triggerWinBack()
    {
        $stats = $this->service->generateWinBackCodes();
        return response()->json([
            'message' => 'Win-back code generation complete.',
            'stats'   => $stats,
        ]);
    }

    /**
     * POST /admin/promo-codes/expire
     * Manually trigger expiry sweep.
     */
    public function triggerExpire()
    {
        $count = $this->service->expireOutdatedCodes();
        return response()->json([
            'message' => "Expired {$count} promo code(s).",
            'count'   => $count,
        ]);
    }

    // ═══════════════════════════════════════════════════
    // CUSTOMER — VALIDATE
    // ═══════════════════════════════════════════════════

    /**
     * POST /customer/promo-codes/validate
     * Validate a promo code at checkout.
     * Returns discount amount preview without applying it.
     */
    public function validateCode(Request $request)
    {
        $request->validate([
            'code'                => 'required|string',
            'order_value'         => 'required|numeric|min:0',
            'referral_discount'   => 'nullable|numeric|min:0',
            'exchange_rate_to_kes'=> 'nullable|numeric|min:0.0001', // ← add
        ]);

        $customer = $request->user()->customer;
        if (!$customer) {
            return response()->json(['valid' => false, 'message' => 'Customer profile not found.'], 404);
        }

        $result = $this->service->validatePromoCode(
            code:             $request->code,
            customer:         $customer,
            orderValue:       (float) $request->order_value,
            referralDiscount: (float) ($request->referral_discount ?? 0),
            exchangeRateToKes:(float) ($request->exchange_rate_to_kes ?? 1.0), // ← add
        );

        if (!$result['valid']) {
            return response()->json($result, 422);
        }

        return response()->json([
            'valid'        => true,
            'message'      => $result['message'],
            'code'         => $result['code']->code,
            'name'         => $result['code']->name,
            'description'  => $result['code']->description,
            'reward_type'  => $result['code']->reward_type,
            'reward_value' => $result['code']->reward_value,
            'discount'     => $result['discount'],
            'stackable'    => $result['code']->stackable,
        ]);
    }

    /**
     * POST /admin/promo-codes/validate
     * Admin version — validate on behalf of a customer.
     */
    public function adminValidate(Request $request)
    {
        $request->validate([
            'code'                => 'required|string',
            'order_value'         => 'required|numeric|min:0',
            'customer_id'         => 'required|exists:customers,id',
            'referral_discount'   => 'nullable|numeric|min:0',
            'exchange_rate_to_kes'=> 'nullable|numeric|min:0.0001', // ← add
        ]);

        $customer = Customer::findOrFail($request->customer_id);

        $result = $this->service->validatePromoCode(
            code:             $request->code,
            customer:         $customer,
            orderValue:       (float) $request->order_value,
            referralDiscount: (float) ($request->referral_discount ?? 0),
            exchangeRateToKes:(float) ($request->exchange_rate_to_kes ?? 1.0), // ← add
        );

        if (!$result['valid']) {
            return response()->json($result, 422);
        }

        return response()->json([
            'valid'        => true,
            'message'      => $result['message'],
            'code'         => $result['code']->code,
            'name'         => $result['code']->name,
            'description'  => $result['code']->description,
            'reward_type'  => $result['code']->reward_type,
            'reward_value' => $result['code']->reward_value,
            'discount'     => $result['discount'],
            'stackable'    => $result['code']->stackable,
        ]);
    }

    // ═══════════════════════════════════════════════════
    // CUSTOMER — MY CODES
    // ═══════════════════════════════════════════════════

    /**
     * GET /customer/promo-codes/my-codes
     * Return all promo codes for the authenticated customer.
     */
    public function myCodes(Request $request)
    {
        $customer = $request->user()->customer;
        if (!$customer) {
            return response()->json(['message' => 'Customer profile not found.'], 404);
        }

        $grouped = $this->service->getCustomerPromoCodes($customer);

        return response()->json([
            'active_codes'  => $grouped['active_codes'],
            'used_codes'    => $grouped['used_codes'],
            'expired_codes' => $grouped['expired_codes'],
            'total_savings' => $grouped['active_codes']->sum(fn($c) =>
                $c->reward_type === 'fixed_amount' ? $c->reward_value : 0
            ),
        ]);
    }

    public function redemptions(Request $request, $id): JsonResponse
    {
        // Standard orders that used this promo code
        $standardOrders = Order::withTrashed()
            ->where('promo_code_id', $id)
            ->with('customer:id,first_name,last_name,email')
            ->select('id','order_number','customer_id','subtotal_kes','promo_discount','total_kes','status','created_at')
            ->orderByDesc('created_at')
            ->get()
            ->map(fn($o) => [
                'order_id'       => $o->id,
                'order_number'   => $o->order_number,
                'order_type'     => 'standard',
                'customer_name'  => $o->customer ? trim($o->customer->first_name . ' ' . $o->customer->last_name) : '—',
                'customer_email' => $o->customer?->email ?? '—',
                'subtotal_kes'   => round((float) $o->subtotal_kes, 2),
                'promo_discount' => round((float) $o->promo_discount, 2),
                'total_kes'      => round((float) $o->total_kes, 2),
                'status'         => $o->status,
                'redeemed_at'    => $o->created_at,
            ]);

        // Hamper orders that used this promo code
        $hamperOrders = HamperOrder::where('referral_code_id', $id)
            ->with('customer:id,first_name,last_name,email')
            ->orderByDesc('created_at')
            ->get()
            ->map(fn($o) => [
                'order_id'       => $o->id,
                'order_number'   => $o->order_number,
                'order_type'     => 'hamper',
                'customer_name'  => $o->customer ? trim($o->customer->first_name . ' ' . $o->customer->last_name) : '—',
                'customer_email' => $o->customer?->email ?? '—',
                'subtotal_kes'   => round((float) $o->subtotal, 2),
                'promo_discount' => round((float) $o->discount_amount, 2),
                'total_kes'      => round((float) $o->total, 2),
                'status'         => $o->status,
                'redeemed_at'    => $o->created_at,
            ]);

        $redemptions = $standardOrders->concat($hamperOrders)
            ->sortByDesc('redeemed_at')
            ->values();

        return response()->json(['redemptions' => $redemptions]);
    }
}